version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8

  pre_build:
    commands:
      - echo "Creating role for spinning up resources. Role defined in creation-iam.yml"
      - aws cloudformation deploy --template-file creation-iam.yml --stack-name cf-infra-generic-test-creation-iam --capabilities CAPABILITY_IAM
      - echo $(aws cloudformation describe-stacks --stack-name cf-infra-generic-test-creation-iam) > stack_info.json
  build:
    commands:
      - aws cloudformation deploy --template-file template.yml --stack-name cf-infra-generic-test --role-arn $(python get_creation_role_arn.py)
    finally:
      - rm stack_info.json