version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - aws cloudformation deploy --template-file template.yml --stack-name cf-infra-generic-test
      