AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CreationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
                - 'codebuild.amazonaws.com'
                - 'cloudformation.amazonaws.com'
          Action:
          - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TemporaryPolicyCfInfraGenericTemplate
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: "*"
      Roles:
      - !Ref CreationRole
Outputs:
    CreationRole:
        Value: 
          Fn::GetAtt: CreationRole.Arn
        Export:
            Name: CreationRoleArn